name: Test Frontend
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: docker
            - run: docker build -t barreto/react-app - frontend/Dockerfile.dev .
            - run: docker run -e CI=true barreto/react-app npm test
