version: "3"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
# create this service bellow for run all the tests
# or don't create this service bellow and use "docker exec -it {CONTAINER ID} npm run test" to menu with options
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - /usr/app/node_modules
            - .:/usr/app
        command: ["npm", "run", "test"]        
